Rspec
deikdesign/enumerables pull request #3
Opened 2020-10-21 00:06 UTC by deikdesign

## Add Rspec to methods

2020-10-21 04:13 UTC, moinkhanif requested changes
## Changes Required❗

Hey @deikdesign , thanks for submitting the project. However, there are a few **missing `do` or `end` keywords** that are causing issues. Also, **14 of your tests fail**. Please make sure that all the **tests pass** before submitting a request for review.

Kindly also **fix linter errors** in the pull request. Make sure to **add a pull request description** as well.

I have mentioned the **rest of the required changes in the below comments**. Please fix them

**Happy Coding**

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +          end
- [x] **[REQUIRED]** You have not added `do` after starting `it` block. Please fix it.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +
- [x] **[REQUIRED]** You have not added `end` after finishing `it` block. Please fix it.

- [x] **[REQUIRED]** Please fix this test:
```ruby
Enumerable#my_all return true when all values are true in a hash
     Failure/Error: expect(hash.my_all? { |key, value| value > 7 }).to eql TRUE
     
       expected: true
            got: false
     
       (compared using eql?)
     
       Diff:
       @@ -1 +1 @@
       -true
       +false
       
     # ./spec/methods_spec.rb:74:in `block (3 levels) in <top (required)>'
```

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        expect(hash.my_all? { |key, value| value > 3 }).to eql TRUE
- [x] **[REQUIRED]** You have not added `end` after finishing `it` block. Please fix it.

- [x] **[REQUIRED]** Please fix this test:
```ruby
Enumerable#my_all return false when one value is false in a range
     Failure/Error: expect(hash.my_all? { |key, value| value > 3 }).to eql TRUE
     
       expected: true
            got: false
     
       (compared using eql?)
     
       Diff:
       @@ -1 +1 @@
       -true
       +false
       
     # ./spec/methods_spec.rb:78:in `block (3 levels) in <top (required)>'
```

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +
- [x] **[REQUIRED]** You have not added `end` after finishing `it` block. Please fix it.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +
- [x] **[REQUIRED]** You have not added `end` after finishing `it` block. Please fix it.

- [x] **[REQUIRED]** Please fix this test:
```ruby
Enumerable#my_count? return to an array when no block  and no argument are given
      Failure/Error: expect(array.my_count?).to eql(5)
      
      NoMethodError:
        undefined method `my_count?' for [1, 2, 3, 4, 5]:Array
        Did you mean?  my_count
      # ./spec/methods_spec.rb:136:in `block (3 levels) in <top (required)>'
```

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +          end
- [ ] **[REQUIRED]** Please fix this test:
```ruby
Enumerable#my_each_with_index return correct array
     Failure/Error: expect(range.my_each_with_index { |num, index| num}).to eql(hash)
     
       expected: {:a=>1, :b=>2, :c=>3}
            got: 0..5
     
       (compared using eql?)
     
       Diff:
       @@ -1,4 +1,2 @@
       -:a => 1,
       -:b => 2,
       -:c => 3,
       +0..5
       
     # ./spec/methods_spec.rb:26:in `block (3 levels) in <top (required)>'
```

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +
- [ ] **[REQUIRED]** Please fix this test:
```ruby
Enumerable#my_select returns an array into a range
     Failure/Error: expect(array.my_select { |num| num < 3}).to eql([0, 1, 2])
     
       expected: [0, 1, 2]
            got: [1, 2]
     
       (compared using eql?)
     # ./spec/methods_spec.rb:49:in `block (3 levels) in <top (required)>'
```

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Please fix this test:
```ruby
 Enumerable#my_select returns an array into a hash
     Failure/Error: expect(array.my_select { |key, value| value < 2}).to eql({ c: 3})
     
     NoMethodError:
       undefined method `<' for nil:NilClass
     # ./spec/methods_spec.rb:53:in `block (4 levels) in <top (required)>'
```

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +
- [ ] **[REQUIRED]** Please fix this test:
```ruby
Enumerable#my_all return false when one value is false in a range
     Failure/Error: expect(hash.my_all? { |n| n > 2 }).to eql FALSE
     
     NoMethodError:
       undefined method `>' for [:a, 1]:Array
     # ./spec/methods_spec.rb:66:in `block (4 levels) in <top (required)>'
```

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Please fix this test:
```ruby
 Enumerable#my_all return true when all values are true in a range
     Failure/Error: expect(hash.my_all? { |n| n > 6 }).to eql TRUE
     
     NoMethodError:
       undefined method `>' for [:a, 1]:Array
     # ./spec/methods_spec.rb:70:in `block (4 levels) in <top (required)>'
```

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Please fix this test:
```ruby
Enumerable#my_any? return false when any value is true on a hash
     Failure/Error: expect(range.my_any? { |key, value| value > 2}  ).to eql TRUE
     
     NoMethodError:
       undefined method `>' for nil:NilClass
     # ./spec/methods_spec.rb:99:in `block (4 levels) in <top (required)>'
```

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Please fix this test:
```ruby
Enumerable#my_any? return false when no value is true on a hash
     Failure/Error: expect(range.my_any? { |key, value| value > 6}  ).to eql false
     
     NoMethodError:
       undefined method `>' for nil:NilClass
     # ./spec/methods_spec.rb:103:in `block (4 levels) in <top (required)>'
```

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Please fix this test:
```ruby
 Enumerable#my_count? elements in a range when no block  and no argument are given
      Failure/Error: expect(range.my_count?).to eql(6)
      
      NoMethodError:
        undefined method `my_count?' for 0..5:Range
        Did you mean?  my_count
      # ./spec/methods_spec.rb:140:in `block (3 levels) in <top (required)>'
```

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Please fix this test:
```ruby
Enumerable#my_count? elements in a hash when no block  and no argument are given
      Failure/Error: expect(hash.my_count?).to eql(3)
      
      NoMethodError:
        undefined method `my_count?' for {:a=>1, :b=>2, :c=>3}:Hash
        Did you mean?  my_count
      # ./spec/methods_spec.rb:144:in `block (3 levels) in <top (required)>'
```

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Please fix this test:
```ruby
Enumerable#my_count? return elements when block is given
      Failure/Error: expect(array.my_count? { |x| x == 2}  ).to eql(1)
      
      NoMethodError:
        undefined method `my_count?' for [1, 2, 3, 4, 5]:Array
        Did you mean?  my_count
      # ./spec/methods_spec.rb:148:in `block (3 levels) in <top (required)>'
```

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Please fix this test:
```ruby
Enumerable#my_inject? inject enumerator if arg is given
      Failure/Error: to_a.my_each { |item| int = int.nil? ? item : yield(int, item) }
      
      LocalJumpError:
        no block given (yield)
```

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Use of All Capital `FALSE` is deprecated. Please use the small case `false` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Use of All Capital `FALSE` is deprecated. Please use the small case `false` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Use of All Capital `FALSE` is deprecated. Please use the small case `false` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Use of All Capital `FALSE` is deprecated. Please use the small case `false` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Use of All Capital `FALSE` is deprecated. Please use the small case `false` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +
- [ ] **[REQUIRED]** Use of All Capital `FALSE` is deprecated. Please use the small case `false` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Use of All Capital `FALSE` is deprecated. Please use the small case `false` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Use of All Capital `TRUE` is deprecated. Please use the small case `true` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        expect(hash.my_all? { |key, value| value > 7 }).to eql TRUE
- [ ] **[REQUIRED]** Use of All Capital `TRUE` is deprecated. Please use the small case `true` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        expect(hash.my_all? { |key, value| value > 3 }).to eql TRUE
- [ ] **[REQUIRED]** Use of All Capital `TRUE` is deprecated. Please use the small case `true` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Use of All Capital `TRUE` is deprecated. Please use the small case `true` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +
- [ ] **[REQUIRED]** Use of All Capital `TRUE` is deprecated. Please use the small case `true` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Use of All Capital `TRUE` is deprecated. Please use the small case `true` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Use of All Capital `TRUE` is deprecated. Please use the small case `true` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Use of All Capital `TRUE` is deprecated. Please use the small case `true` instead.

2020-10-21 04:13 UTC, moinkhanif commented on spec/methods_spec.rb
> +        end
- [ ] **[REQUIRED]** Use of All Capital `TRUE` is deprecated. Please use the small case `true` instead.

2020-10-27 19:37 UTC, Temmarie requested changes
## Changes Required! :recycle: 
### Hello Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png)
 
### You have done well so far :clap: However, there are some changes you have to make for your project to be approved. Kindly work on them and submit them for another code review.


 **General**



- [x] Your project looks great. However, your project cannot be approved until you write a descriptive Pull Request Message. It's essential that your repository is professional, as this is one of the things that potential colleagues will look at when recruiting team members. Please refer to [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more information.

**Recommended**

##### PLEASE FIX THESE ERRORS
- [x]  Enumerable#my_any? return false when any value is true on a hash
     Failure/Error: expect(hash.my_any? { |n| n > 2 }).to eql true
          NoMethodError: undefined method `>' for [:a, 1]:Array 

- [ ] Enumerable#my_any? return false when no value is true on a hash
     Failure/Error: expect(hash.my_any? { |n| n > 6 }).to eql false  
     NoMethodError:  undefined method `>' for [:a, 1]:Array


- [ ] Enumerable#my_inject? inject enumerator if arg is given
     Failure/Error: to_a.my_each { |item| int = int.nil? ? item : yield(int, item) }
          LocalJumpError:  no block given (yield)


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review @tamara._ :wink: 
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2020-10-28 17:03 UTC, mahmoud717 approved these changes
## Project approved ✔️  # 

Nice job implementing the required changes, you can go ahead and merge this pull request.

2020-10-30 23:11 UTC, merged